<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
/** @noinspection PhpIncludeInspection */
require APPPATH . '/libraries/REST_Controller.php';

class Data extends REST_Controller {
    function __construct()
    {
        // Construct the parent class
        parent::__construct();

        // Configure limits on our controller methods
        // Ensure you have created the 'limits' table and enabled 'limits' within application/config/rest.php
        $this->methods['data_get']['limit'] = 500;
    }

    public function data_get()
    {
        $message = [
            'idx' => 100, // Automatically generated by the model
            'x' => $this->get('x'),
            'y' => $this->get('y'),
            'z' => $this->get('z')
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }

    public function data_post()
    {
        $message = [
            'idx' => 100, // Automatically generated by the model
            'x' => $this->post('x'),
            'y' => $this->post('y'),
            'z' => $this->post('z')
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
}